samples: config/samples.tsv

genome:
    dir: /home/victor/DataHub/Genomics
    datatype: dna
    species: homo_sapiens
    build: GRCh38
    release: "109"
    flavor: chr_patch_hapl_scaff

fastqs:
    pe: false # pair end
    dir: raw
qc_plot:
    n_genes: 50
    ellipses: true
    ellipse_size: 0.8
dea:
    active: true
    dea_vs:
        - [hSETDB1_sg1,Control_sg2]
        - [Control_sg2,hSETDB1_sg1]
    logFC: 0.585
    pvalue: 0.05

warpper_mirror: https://jihulab.com/BioQuest/snakemake-wrappers/raw/v1.29.0/